export const siteConfig = {
  name: "Tanishq",
  logo: "TANISHQ",
  tagline: "Crafting playful, considered software.",
  socials: [
    {
      label: "LinkedIn",
      href: "https://linkedin.com/in/tanishq-bhosale",
    },
    {
      label: "GitHub",
      href: "https://github.com/TanishqBhosale",
    },
  ],
  nav: [
    { label: "Home", href: "/" },
    { label: "Work", href: "/#work" },
    { label: "About", href: "/#about" },
    { label: "Let's talk", href: "/#contact" },
  ],
  hero: {
    wordmark: "TANISHQ",
    background: "#FF5A52",
    wordmarkColor: "#FFC9C5",
    accentColor: "#E4FE52",
  },
  crafty: {
    background: "#FF5A52",
    textColor: "#FFC9C5",
    headline: ["A crafty bunch", "of creative", "problem solvers."],
    bgVideo: {
      poster:
        "https://cdn.prod.website-files.com/699637b29cf8a85d12ebac48/69aaa9d802173759e72876ed_hero_logo_loop-good_poster.0000000.jpg",
      mp4: "https://cdn.prod.website-files.com/699637b29cf8a85d12ebac48/69aaa9d802173759e72876ed_hero_logo_loop-good_mp4.mp4",
      webm: "https://cdn.prod.website-files.com/699637b29cf8a85d12ebac48/69aaa9d802173759e72876ed_hero_logo_loop-good_webm.webm",
    },
    stickerColors: {
      face: "#E4FE52",
      side: "#A8C220",
      text: "#FF3B33",
    },
    stickers: [
      { label: "ANIMATION", position: "top", rotate: -10 },
      { label: "LIVE ACTION", position: "middle", rotate: 8 },
      { label: "WIZARDRY", position: "bottom", rotate: -7 },
    ],
  },
  about: {
    background: "#2D00F7",
    textColor: "#E0C8BB",
    accent: "#FFE6D6",
    eyebrow: "About",
    name: "Tanishq Bhosale.",
    role: "Full Stack + AI Engineer · Bangalore",
    intro:
      "Two-plus years shipping production LLM and agentic AI systems — LangGraph state machines, FastAPI streams, React Native interfaces. I care about the moment where a complex system feels obvious to use, even when the plumbing underneath isn't.",
    sub: "Currently at Tap Academy (Full Stack) and Quanta (SDE1). Previously interned at Visionet Systems. B.Tech in Computer Science (Data Science), Presidency University, 2020–2024.",
    skills: [
      {
        title: "AI / ML",
        items: [
          "LangGraph",
          "LangChain",
          "LLM Integration",
          "RAG",
          "pgvector",
          "Agentic Workflows",
          "Prompt Engineering",
          "Mem0",
        ],
      },
      {
        title: "Languages",
        items: ["Python", "JavaScript", "TypeScript"],
      },
      {
        title: "Frontend",
        items: [
          "React",
          "React Native",
          "Expo",
          "Redux",
          "Zustand",
          "Tailwind CSS",
        ],
      },
      {
        title: "Backend",
        items: ["FastAPI", "Node.js", "Express", "Flask", "Prisma"],
      },
      {
        title: "Databases",
        items: ["PostgreSQL", "MongoDB", "MySQL", "pgvector"],
      },
      {
        title: "Cloud",
        items: ["AWS", "Firebase", "Supabase"],
      },
      {
        title: "Other",
        items: [
          "RESTful APIs",
          "SSE Streaming",
          "Async Architecture",
          "Modular Architecture",
          "SQL Optimization",
        ],
      },
    ],
    marquee: [
      "Full Stack",
      "AI Engineer",
      "LangGraph",
      "FastAPI",
      "React Native",
      "pgvector",
      "Agentic AI",
      "Streaming",
      "✦",
    ],
  },
  education: {
    background: "#0E2A1E",
    cardStock: "#F4ECD6",
    inkColor: "#0E2A1E",
    bodyColor: "#D6E8C5",
    accent: "#E4FE52",
    red: "#FF3B33",
    eyebrow: "Education",
    classOf: "2024",
    duration: "Class of",
    card: {
      university: "Presidency University",
      shortName: "PU · BANGALORE",
      name: "Tanishq Bhosale",
      degree: "B.Tech · CSE (Data Science)",
      batch: "2020 — 2024",
      idNumber: "PU-19BCE-7421",
      issued: "AUG 2020",
      cgpa: "7.95",
      address: "Itgalpur, Rajanakunte, Yelahanka, Bangalore — 560064",
      validThrough: "2024",
    },
    courses: [
      { code: "CSE-101", title: "Foundations of Computer Science" },
      { code: "CSE-201", title: "Data Structures & Algorithms" },
      { code: "CSE-305", title: "Database Management Systems" },
      { code: "ML-401", title: "Machine Learning" },
      { code: "DS-402", title: "Big Data Systems" },
      { code: "DS-501", title: "Final-Year Capstone" },
    ],
    stats: [
      "4 years",
      "8 semesters",
      "47 papers",
      "CGPA 7.95",
      "Bangalore, IN",
      "Graduated ✓",
    ],
    closer: "Where the foundations got laid.",
  },
  contact: {
    background: "#0A0A0A",
    textColor: "#FFFFFF",
    muted: "#9A9A9A",
    accent: "#E4FE52",
    red: "#FF3B33",
    eyebrow: "Contact",
    statusLabel: "Transmission Open",
    headline: ["Let's", "talk."],
    intro:
      "Got a system to design, an LLM to wrangle, a feature to ship — or just want to say hi. Pick a frequency, I'm listening.",
    available: {
      label: "Available now",
      location: "Bangalore",
      timezone: "Asia/Kolkata",
      timezoneShort: "IST",
    },
    primary: {
      label: "Drop me a line",
      email: "bhosaletanishq4@gmail.com",
      mailto:
        "mailto:bhosaletanishq4@gmail.com?subject=Let%27s%20build%20something",
    },
    channels: [
      {
        id: "phone",
        label: "Phone",
        value: "+91 6362157894",
        href: "tel:+916362157894",
        glyph: "tel",
      },
      {
        id: "linkedin",
        label: "LinkedIn",
        value: "@tanishq-bhosale",
        href: "https://linkedin.com/in/tanishq-bhosale",
        glyph: "in",
      },
      {
        id: "github",
        label: "GitHub",
        value: "@TanishqBhosale",
        href: "https://github.com/TanishqBhosale",
        glyph: "gh",
      },
    ],
    resume: {
      label: "Download Resume",
      sub: "PDF · 2 pages",
      href: "/Tanishq_Bhosale.pdf",
      fileName: "Tanishq_Bhosale.pdf",
    },
    closer: "TX // signing off — your move.",
  },
  experience: {
    background: "#F4ECD6",
    ticketBg: "#FFFAF0",
    textColor: "#2A1810",
    accent: "#FF3B33",
    eyebrow: "Experience",
    status: "Available for GenAI / AI Engineer roles · Bangalore",
    jobs: [
      {
        serial: "T-001",
        company: "Tap Academy",
        role: "Full Stack Engineer",
        location: "Bangalore",
        dates: "Mar 2025 — Present",
        current: true,
        stampSub: "2026",
        stars: 5,
        bullets: [
          "Built production LLM-powered AI code assistance feature using OpenAI APIs with optimized prompt engineering and token management, serving real-time suggestions to students on the learning platform.",
          "Developed scalable full-stack applications with React + FastAPI/Node.js, implementing Redux state management and React Router for a responsive learning experience.",
          "Optimized PostgreSQL and MongoDB queries through indexing and query restructuring, reducing average API response time by ~35%.",
          "Integrated streaming LLM responses via Server-Sent Events for instant feedback on code submissions, improving perceived responsiveness.",
        ],
        stack: [
          "React",
          "FastAPI",
          "Node.js",
          "PostgreSQL",
          "MongoDB",
          "Redux",
          "SSE",
          "OpenAI",
        ],
        rotate: -1.5,
      },
      {
        serial: "T-002",
        company: "Quanta",
        role: "Software Development Engineer 1",
        location: "Bangalore",
        dates: "Jul 2024 — Present",
        current: true,
        stampSub: "2026",
        stars: 4,
        bullets: [
          "Designed high-performance FastAPI and Flask APIs for real-time synchronization and collaboration features, handling concurrent user sessions with low-latency updates.",
          "Built scalable MySQL schemas and integrated third-party APIs for production workloads, reducing data inconsistency issues.",
          "Contributed to modular backend architecture with reusable service layers, cutting new feature development time for adjacent modules.",
        ],
        stack: ["FastAPI", "Flask", "MySQL", "Async", "REST"],
        rotate: 1.2,
      },
      {
        serial: "T-003",
        company: "Visionet Systems",
        role: "Software Developer Intern",
        location: "Bangalore",
        dates: "Feb 2024 — Jul 2024",
        current: false,
        stampSub: "Jul 24",
        stars: 3,
        bullets: [
          "Built reusable AWS cloud components and modular Python solutions with optimized SQL queries, improving scalability and data integrity.",
        ],
        stack: ["AWS", "Python", "SQL"],
        rotate: -0.8,
      },
    ],
  },
  directors: {
    background: "#E0C8BB",
    textColor: "#2A1810",
    accentColor: "#FF3B33",
    items: [
      {
        name: "AI Code Editor",
        image: "/projects/AICodeEditor.png",
        href: "",
      },
      {
        name: "MindSnack Quiz Builder",
        image: "/projects/MindSnackQuizBuilder.png",
        href: "",
      },
      {
        name: "Ethereum Price Prediction",
        image: "/projects/EthereumFuturePricePrediction.png",
        href: "",
      },
      {
        name: "Financial Fraud Prediction",
        image: "/projects/FinancialFraudPrediction.png",
        href: "",
      },
      {
        name: "Food Delivery Data Analysis",
        image: "/projects/FoodDeliveryDataAnalysis.png",
        href: "",
      },
      {
        name: "Website Auto Nxtgen",
        image: "/projects/WebsiteAutoNxtgen.png",
        href: "",
      },
    ],
  },
} as const;

export type NavItem = (typeof siteConfig.nav)[number];
